server:
  port: 8082

spring:
  application:
    name: "productservice"

  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: monkdevs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/







