spring:
  application:
    name: UserAuthService
  security: # OAuth2 Configuration
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

  datasource:
    url: jdbc:postgresql://localhost:5432/userauth
    username: postgres
    password: monkdevs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app:
  jwt:
    secret: YourJWTSecretKey
    expirationMs: 86400000 # 1 day in milliseconds


